source 'git@bitbucket.org:mmulyar/mmpods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SectionDataSource_Tests' do
  pod 'SectionDataSource', :path => '../'
                                   
end
