platform :ios, '8.0'

source 'git@bitbucket.org:mmulyar/mmpods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SectionDataSourceExample' do
    pod 'SectionDataSource', :path => '../'
    pod 'Hue'
end

target 'SectionDataSource_Tests' do
  pod 'SectionDataSource', :path => '../'
end
